[package]
name = "kcat"
version = "0.1.0"
authors = ["Xavier Stevens <xavier.stevens@gmail.com>"]

[dependencies]
clap = "2"
futures = "0.1.25"

[dependencies.rdkafka]
version = "0.17.0"
features = ["ssl", "sasl"]

[profile.release]
lto = true
